{
    "swagger": "2.0",
    "info": {
        "version": "1.0",
        "title": "UL MOODLE API",
        "description": "# Intro\nThis is the API to connect the University of Liberia's Moodle instance to SchooLink. All API calls require an API key that should set as an HTTP Header in the format: 'Authorization:API_KEY'. \n\nExample: \ncurl -i -H 'Accept:application/json' -H 'Authorization:API_KEY' \\ https://api.elearning.ul.edu.lr/api/v1/users\n\nTo get a key or get support, kindly contact Kwagei Group at info@kwagei.com.",
        "contact": {}
    },
    "host": "api.elearning.ul.edu.lr",
    "basePath": "/api/v1",
    "securityDefinitions": {
        "authorization": {
            "type": "apiKey",
            "description": "",
            "name": "authorization",
            "in": "header"
        }
    },
    "schemes": [
        "https"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/users": {
            "get": {
                "description": "Return all users. Does not take any parameters.",
                "summary": "All Users",
                "tags": [
                    "Misc"
                ],
                "operationId": "AllUsers",
                "deprecated": false,
                "produces": [
                    "application/json; charset=utf-8"
                ],
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/AllUsers"
                        },
                        "examples": {
                            "application/json; charset=utf-8": {
                                "users": [{
                                        "id": "bb1c09c9-afa0-4cce-bd37-92c39397fba1",
                                        "schoolink_record_id": "383jdj8jdhdyeue",
                                        "username": "001120",
                                        "password": "5ebe2294ecd0e0f08eab7690d2a6ee69",
                                        "ul_email": "blamauldoe@example.com",
                                        "personal_email": "blamadoe@example.com",
                                        "telephone_number": "0778522524",
                                        "user_type": "student",
                                        "gender": "Male",
                                        "college": "William R. Tolbert, Jr. College of Agriculture and Forestry",
                                        "department": "Department of General Agriculture - BSc",
                                        "major": "",
                                        "account_status": "active",
                                        "created_at": "2020-07-20T01:14:53.58Z",
                                        "updated_at": "2020-07-20T01:14:53.58Z"
                                    },
                                    {
                                        "id": "57864d18-636b-48fe-8467-4652bfe1722c",
                                        "schoolink_record_id": "bbkdkejdj8jdhdyeue",
                                        "username": "001121",
                                        "password": "5ebe2294ecd0e0f08eab7690d2a6ee69",
                                        "ul_email": "johndoeul@example.com",
                                        "personal_email": "johndoe@example.com",
                                        "telephone_number": "0888522524",
                                        "user_type": "student",
                                        "gender": "Male",
                                        "college": "College of Business and Public Administration (BBA/BPA)",
                                        "department": "Department of Business Adm. in Accounting â€“ BBA",
                                        "major": "",
                                        "account_status": "active",
                                        "created_at": "2020-07-20T01:14:53.58Z",
                                        "updated_at": "2020-07-20T01:14:53.58Z"
                                    },
                                    {
                                        "id": "8e67fe1f-2e8a-4e32-b8d6-427cae889f4e",
                                        "schoolink_record_id": "3dss983jdj8jdhdyeue",
                                        "username": "Konah Doe",
                                        "password": "5ebe2294ecd0e0f08eab7690d2a6ee69",
                                        "ul_email": "konahdoeule@example.com",
                                        "personal_email": "konahdoe@example.com",
                                        "telephone_number": "0886522524",
                                        "user_type": "faculty",
                                        "gender": "Female",
                                        "college": "",
                                        "department": "",
                                        "major": "",
                                        "account_status": "active",
                                        "created_at": "2020-07-20T01:14:53.58Z",
                                        "updated_at": "2020-07-20T01:14:53.58Z"
                                    }
                                ]
                            }
                        },
                        "headers": {
                            "Server": {
                                "type": "string",
                                "default": "nginx/1.17.10 (Ubuntu)"
                            },
                            "Date": {
                                "type": "string",
                                "default": "Mon, 20 Jul 2020 01:15:26 GMT"
                            },
                            "Content-Length": {
                                "type": "string",
                                "default": "1556"
                            },
                            "Connection": {
                                "type": "string",
                                "default": "keep-alive"
                            },
                            "X-DNS-Prefetch-Control": {
                                "type": "string",
                                "default": "off"
                            },
                            "X-Frame-Options": {
                                "type": "string",
                                "default": "SAMEORIGIN"
                            },
                            "Strict-Transport-Security": {
                                "type": "string",
                                "default": "max-age=15552000; includeSubDomains"
                            },
                            "X-Download-Options": {
                                "type": "string",
                                "default": "noopen"
                            },
                            "X-Content-Type-Options": {
                                "type": "string",
                                "default": "nosniff"
                            },
                            "X-XSS-Protection": {
                                "type": "string",
                                "default": "1; mode=block"
                            },
                            "ETag": {
                                "type": "string",
                                "default": "W/\"614-p9TkiuM1AIdDxd+wiNa8up6WH9M\""
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new user\n\nReturns message **User created successfully** and the newly created user when successful",
                "summary": "Create User",
                "tags": [
                    "Misc"
                ],
                "operationId": "CreateUser",
                "deprecated": false,
                "produces": [
                    "application/json; charset=utf-8"
                ],
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "parameters": [{
                        "name": "schoolink_record_id",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "username",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "personal_email",
                        "in": "formData",
                        "required": false,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "ul_email",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "password",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "telephone_number",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "user_type",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "gender",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "college",
                        "in": "formData",
                        "required": false,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "department",
                        "in": "formData",
                        "required": false,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "major",
                        "in": "formData",
                        "required": false,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "account_status",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "description": ""
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/CreateUser"
                        },
                        "examples": {
                            "application/json; charset=utf-8": {
                                "message": "User created successfully",
                                "data": {
                                    "id": "a1bbf48b-d811-43f2-af2b-61d508462da3",
                                    "schoolink_record_id": "5303jdj8jdhdyeue",
                                    "username": "09890",
                                    "personal_email": "testuser@example.com",
                                    "ul_email": "testuserul@example.com",
                                    "password": "90be22ecd0e0f08eab7690d2a6ee69",
                                    "telephone_number": "0778909090",
                                    "user_type": "student",
                                    "gender": "Female",
                                    "college": "William R. Tolbert, Jr. College of Agriculture and Forestry",
                                    "department": "Department of General Agriculture - BSc",
                                    "major": "",
                                    "updated_at": "2020-07-20T01:17:28.482Z",
                                    "created_at": "2020-07-20T01:17:28.482Z",
                                    "account_status": null
                                }
                            }
                        },
                        "headers": {
                            "Server": {
                                "type": "string",
                                "default": "nginx/1.17.10 (Ubuntu)"
                            },
                            "Date": {
                                "type": "string",
                                "default": "Mon, 20 Jul 2020 01:17:28 GMT"
                            },
                            "Content-Length": {
                                "type": "string",
                                "default": "584"
                            },
                            "Connection": {
                                "type": "string",
                                "default": "keep-alive"
                            },
                            "X-DNS-Prefetch-Control": {
                                "type": "string",
                                "default": "off"
                            },
                            "X-Frame-Options": {
                                "type": "string",
                                "default": "SAMEORIGIN"
                            },
                            "Strict-Transport-Security": {
                                "type": "string",
                                "default": "max-age=15552000; includeSubDomains"
                            },
                            "X-Download-Options": {
                                "type": "string",
                                "default": "noopen"
                            },
                            "X-Content-Type-Options": {
                                "type": "string",
                                "default": "nosniff"
                            },
                            "X-XSS-Protection": {
                                "type": "string",
                                "default": "1; mode=block"
                            },
                            "ETag": {
                                "type": "string",
                                "default": "W/\"248-UTxRR0CvAvIHrIuQg9l5zdFzH7s\""
                            }
                        }
                    }
                }
            }
        },
        "/users/bbkdkejdj8jdhdyeue": {
            "get": {
                "description": "Gets details of a particular user by passing the schoolink_record_id. The field, schoolink_record_id, is the database index of the user record in the SchooLink database. Given that usernames vary between students (student id) and faculty (username), the schoolink_record_id is used as the most standardized identifier for user records.",
                "summary": "Get User",
                "tags": [
                    "Misc"
                ],
                "operationId": "GetUser",
                "deprecated": false,
                "produces": [
                    "application/json; charset=utf-8"
                ],
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/GetUser"
                        },
                        "examples": {
                            "application/json; charset=utf-8": {
                                "message": "User found successfully",
                                "data": {
                                    "id": "57864d18-636b-48fe-8467-4652bfe1722c",
                                    "schoolink_record_id": "bbkdkejdj8jdhdyeue",
                                    "username": "001121",
                                    "password": "5ebe2294ecd0e0f08eab7690d2a6ee69",
                                    "ul_email": "johndoeul@example.com",
                                    "personal_email": "johndoe@example.com",
                                    "telephone_number": "0888522524",
                                    "user_type": "student",
                                    "gender": "Male",
                                    "college": "College of Business and Public Administration (BBA/BPA)",
                                    "department": "Department of Business Adm. in Accounting â€“ BBA",
                                    "major": "",
                                    "account_status": "active",
                                    "created_at": "2020-07-20T01:14:53.58Z",
                                    "updated_at": "2020-07-20T01:14:53.58Z"
                                }
                            }
                        },
                        "headers": {
                            "Server": {
                                "type": "string",
                                "default": "nginx/1.17.10 (Ubuntu)"
                            },
                            "Date": {
                                "type": "string",
                                "default": "Mon, 20 Jul 2020 01:16:13 GMT"
                            },
                            "Content-Length": {
                                "type": "string",
                                "default": "593"
                            },
                            "Connection": {
                                "type": "string",
                                "default": "keep-alive"
                            },
                            "X-DNS-Prefetch-Control": {
                                "type": "string",
                                "default": "off"
                            },
                            "X-Frame-Options": {
                                "type": "string",
                                "default": "SAMEORIGIN"
                            },
                            "Strict-Transport-Security": {
                                "type": "string",
                                "default": "max-age=15552000; includeSubDomains"
                            },
                            "X-Download-Options": {
                                "type": "string",
                                "default": "noopen"
                            },
                            "X-Content-Type-Options": {
                                "type": "string",
                                "default": "nosniff"
                            },
                            "X-XSS-Protection": {
                                "type": "string",
                                "default": "1; mode=block"
                            },
                            "ETag": {
                                "type": "string",
                                "default": "W/\"251-wdwgUVMc0W26ryEvj/m2N9HHFGo\""
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a user. Users are identified by schoolink_record_id. This field is required. All other fields are optional.\n\nPass the field and value that you want to update and the field will be updated with the new values. All other fields will remain the same.\n\nYou can verify the record changed by using the Get User endpoint above.\n\nReturns **User updated successfully** when successful and the updated user record",
                "summary": "Update User",
                "tags": [
                    "Misc"
                ],
                "operationId": "UpdateUser",
                "deprecated": false,
                "produces": [
                    "application/json; charset=utf-8"
                ],
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "parameters": [{
                        "name": "schoolink_record_id",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "username",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "password",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "personal_email",
                        "in": "formData",
                        "required": false,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "ul_email",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "telephone_number",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "user_type",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "gender",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "college",
                        "in": "formData",
                        "required": false,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "department",
                        "in": "formData",
                        "required": false,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "major",
                        "in": "formData",
                        "required": false,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "account_status",
                        "in": "formData",
                        "required": true,
                        "type": "string",
                        "description": ""
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/UpdateUser"
                        },
                        "examples": {
                            "application/json; charset=utf-8": {
                                "message": "User updated successfully",
                                "data": {
                                    "id": "57864d18-636b-48fe-8467-4652bfe1722c",
                                    "schoolink_record_id": "bbkdkejdj8jdhdyeue",
                                    "username": "001121",
                                    "password": "5ebe2294ecd0e0f08eab7690d2a6ee69",
                                    "ul_email": "johndoeul@example.com",
                                    "personal_email": "johndoe@example.com",
                                    "telephone_number": "0888522524",
                                    "user_type": "student",
                                    "gender": "Male",
                                    "college": "College of Business and Public Administration (BBA/BPA)",
                                    "department": "Department of Business Adm. in Accounting â€“ BBA",
                                    "major": "My new major",
                                    "account_status": "active",
                                    "created_at": "2020-07-20T01:14:53.58Z",
                                    "updated_at": "2020-07-20T01:18:39.665Z"
                                }
                            }
                        },
                        "headers": {
                            "Server": {
                                "type": "string",
                                "default": "nginx/1.17.10 (Ubuntu)"
                            },
                            "Date": {
                                "type": "string",
                                "default": "Mon, 20 Jul 2020 01:18:39 GMT"
                            },
                            "Content-Length": {
                                "type": "string",
                                "default": "607"
                            },
                            "Connection": {
                                "type": "string",
                                "default": "keep-alive"
                            },
                            "X-DNS-Prefetch-Control": {
                                "type": "string",
                                "default": "off"
                            },
                            "X-Frame-Options": {
                                "type": "string",
                                "default": "SAMEORIGIN"
                            },
                            "Strict-Transport-Security": {
                                "type": "string",
                                "default": "max-age=15552000; includeSubDomains"
                            },
                            "X-Download-Options": {
                                "type": "string",
                                "default": "noopen"
                            },
                            "X-Content-Type-Options": {
                                "type": "string",
                                "default": "nosniff"
                            },
                            "X-XSS-Protection": {
                                "type": "string",
                                "default": "1; mode=block"
                            },
                            "ETag": {
                                "type": "string",
                                "default": "W/\"25f-Vy2AcN9m5QMxahIuDaMcMGZtoIA\""
                            }
                        }
                    }
                }
            }
        },
        "/users/5303jdj8jdhdyeue": {
            "delete": {
                "description": "Delete a user by passing the user's schoolink_record_id\n\nReturns message **User deleted successfully** when OK",
                "summary": "Delete User",
                "tags": [
                    "Misc"
                ],
                "operationId": "DeleteUser",
                "deprecated": false,
                "produces": [
                    "application/json; charset=utf-8"
                ],
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/DeleteUser"
                        },
                        "examples": {
                            "application/json; charset=utf-8": {
                                "message": "User deleted successfully"
                            }
                        },
                        "headers": {
                            "X-DNS-Prefetch-Control": {
                                "type": "string",
                                "default": "off"
                            },
                            "X-Frame-Options": {
                                "type": "string",
                                "default": "SAMEORIGIN"
                            },
                            "Strict-Transport-Security": {
                                "type": "string",
                                "default": "max-age=15552000; includeSubDomains"
                            },
                            "X-Download-Options": {
                                "type": "string",
                                "default": "noopen"
                            },
                            "X-Content-Type-Options": {
                                "type": "string",
                                "default": "nosniff"
                            },
                            "X-XSS-Protection": {
                                "type": "string",
                                "default": "1; mode=block"
                            },
                            "Content-Length": {
                                "type": "string",
                                "default": "39"
                            },
                            "ETag": {
                                "type": "string",
                                "default": "W/\"27-27o4zzUjhHNmthTJyia4gBCjpos\""
                            },
                            "Date": {
                                "type": "string",
                                "default": "Sun, 19 Jul 2020 18:00:59 GMT"
                            },
                            "Connection": {
                                "type": "string",
                                "default": "keep-alive"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AllUsers": {
            "title": "AllUsers",
            "example": {
                "users": [{
                        "id": "bb1c09c9-afa0-4cce-bd37-92c39397fba1",
                        "schoolink_record_id": "383jdj8jdhdyeue",
                        "username": "001120",
                        "password": "5ebe2294ecd0e0f08eab7690d2a6ee69",
                        "ul_email": "blamauldoe@example.com",
                        "personal_email": "blamadoe@example.com",
                        "telephone_number": "0778522524",
                        "user_type": "student",
                        "gender": "Male",
                        "college": "William R. Tolbert, Jr. College of Agriculture and Forestry",
                        "department": "Department of General Agriculture - BSc",
                        "major": "",
                        "account_status": "active",
                        "created_at": "2020-07-20T01:14:53.58Z",
                        "updated_at": "2020-07-20T01:14:53.58Z"
                    },
                    {
                        "id": "57864d18-636b-48fe-8467-4652bfe1722c",
                        "schoolink_record_id": "bbkdkejdj8jdhdyeue",
                        "username": "001121",
                        "password": "5ebe2294ecd0e0f08eab7690d2a6ee69",
                        "ul_email": "johndoeul@example.com",
                        "personal_email": "johndoe@example.com",
                        "telephone_number": "0888522524",
                        "user_type": "student",
                        "gender": "Male",
                        "college": "College of Business and Public Administration (BBA/BPA)",
                        "department": "Department of Business Adm. in Accounting â€“ BBA",
                        "major": "",
                        "account_status": "active",
                        "created_at": "2020-07-20T01:14:53.58Z",
                        "updated_at": "2020-07-20T01:14:53.58Z"
                    },
                    {
                        "id": "8e67fe1f-2e8a-4e32-b8d6-427cae889f4e",
                        "schoolink_record_id": "3dss983jdj8jdhdyeue",
                        "username": "Konah Doe",
                        "password": "5ebe2294ecd0e0f08eab7690d2a6ee69",
                        "ul_email": "konahdoeule@example.com",
                        "personal_email": "konahdoe@example.com",
                        "telephone_number": "0886522524",
                        "user_type": "faculty",
                        "gender": "Female",
                        "college": "",
                        "department": "",
                        "major": "",
                        "account_status": "active",
                        "created_at": "2020-07-20T01:14:53.58Z",
                        "updated_at": "2020-07-20T01:14:53.58Z"
                    }
                ]
            },
            "type": "object",
            "properties": {
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/User"
                    }
                }
            },
            "required": [
                "users"
            ]
        },
        "User": {
            "title": "User",
            "example": {
                "id": "bb1c09c9-afa0-4cce-bd37-92c39397fba1",
                "schoolink_record_id": "383jdj8jdhdyeue",
                "username": "001120",
                "password": "5ebe2294ecd0e0f08eab7690d2a6ee69",
                "ul_email": "blamauldoe@example.com",
                "personal_email": "blamadoe@example.com",
                "telephone_number": "0778522524",
                "user_type": "student",
                "gender": "Male",
                "college": "William R. Tolbert, Jr. College of Agriculture and Forestry",
                "department": "Department of General Agriculture - BSc",
                "major": "",
                "account_status": "active",
                "created_at": "2020-07-20T01:14:53.58Z",
                "updated_at": "2020-07-20T01:14:53.58Z"
            },
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "schoolink_record_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "ul_email": {
                    "type": "string"
                },
                "personal_email": {
                    "type": "string"
                },
                "telephone_number": {
                    "type": "string"
                },
                "user_type": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "college": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "account_status": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            },
            "required": [
                "id",
                "schoolink_record_id",
                "username",
                "password",
                "ul_email",
                "personal_email",
                "telephone_number",
                "user_type",
                "gender",
                "college",
                "department",
                "major",
                "account_status",
                "created_at",
                "updated_at"
            ]
        },
        "GetUser": {
            "title": "GetUser",
            "example": {
                "message": "User found successfully",
                "data": {
                    "id": "57864d18-636b-48fe-8467-4652bfe1722c",
                    "schoolink_record_id": "bbkdkejdj8jdhdyeue",
                    "username": "001121",
                    "password": "5ebe2294ecd0e0f08eab7690d2a6ee69",
                    "ul_email": "johndoeul@example.com",
                    "personal_email": "johndoe@example.com",
                    "telephone_number": "0888522524",
                    "user_type": "student",
                    "gender": "Male",
                    "college": "College of Business and Public Administration (BBA/BPA)",
                    "department": "Department of Business Adm. in Accounting â€“ BBA",
                    "major": "",
                    "account_status": "active",
                    "created_at": "2020-07-20T01:14:53.58Z",
                    "updated_at": "2020-07-20T01:14:53.58Z"
                }
            },
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/Data"
                }
            },
            "required": [
                "message",
                "data"
            ]
        },
        "Data": {
            "title": "Data",
            "example": {
                "id": "57864d18-636b-48fe-8467-4652bfe1722c",
                "schoolink_record_id": "bbkdkejdj8jdhdyeue",
                "username": "001121",
                "password": "5ebe2294ecd0e0f08eab7690d2a6ee69",
                "ul_email": "johndoeul@example.com",
                "personal_email": "johndoe@example.com",
                "telephone_number": "0888522524",
                "user_type": "student",
                "gender": "Male",
                "college": "College of Business and Public Administration (BBA/BPA)",
                "department": "Department of Business Adm. in Accounting â€“ BBA",
                "major": "",
                "account_status": "active",
                "created_at": "2020-07-20T01:14:53.58Z",
                "updated_at": "2020-07-20T01:14:53.58Z"
            },
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "schoolink_record_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "ul_email": {
                    "type": "string"
                },
                "personal_email": {
                    "type": "string"
                },
                "telephone_number": {
                    "type": "string"
                },
                "user_type": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "college": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "account_status": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            },
            "required": [
                "id",
                "schoolink_record_id",
                "username",
                "password",
                "ul_email",
                "telephone_number",
                "user_type",
                "gender",
                "account_status"
            ]
        },
        "CreateUser": {
            "title": "CreateUser",
            "example": {
                "message": "User created successfully",
                "data": {
                    "id": "a1bbf48b-d811-43f2-af2b-61d508462da3",
                    "schoolink_record_id": "5303jdj8jdhdyeue",
                    "username": "09890",
                    "personal_email": "testuser@example.com",
                    "ul_email": "testuserul@example.com",
                    "password": "90be22ecd0e0f08eab7690d2a6ee69",
                    "telephone_number": "0778909090",
                    "user_type": "student",
                    "gender": "Female",
                    "college": "William R. Tolbert, Jr. College of Agriculture and Forestry",
                    "department": "Department of General Agriculture - BSc",
                    "major": "",
                    "updated_at": "2020-07-20T01:17:28.482Z",
                    "created_at": "2020-07-20T01:17:28.482Z",
                    "account_status": null
                }
            },
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/Data1"
                }
            },
            "required": [
                "message",
                "data"
            ]
        },
        "Data1": {
            "title": "Data1",
            "example": {
                "id": "a1bbf48b-d811-43f2-af2b-61d508462da3",
                "schoolink_record_id": "5303jdj8jdhdyeue",
                "username": "09890",
                "personal_email": "testuser@example.com",
                "ul_email": "testuserul@example.com",
                "password": "90be22ecd0e0f08eab7690d2a6ee69",
                "telephone_number": "0778909090",
                "user_type": "student",
                "gender": "Female",
                "college": "William R. Tolbert, Jr. College of Agriculture and Forestry",
                "department": "Department of General Agriculture - BSc",
                "major": "",
                "updated_at": "2020-07-20T01:17:28.482Z",
                "created_at": "2020-07-20T01:17:28.482Z",
                "account_status": null
            },
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "schoolink_record_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "personal_email": {
                    "type": "string"
                },
                "ul_email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "telephone_number": {
                    "type": "string"
                },
                "user_type": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "college": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "account_status": {
                    "type": "string"
                }
            },
            "required": [
                "id",
                "schoolink_record_id",
                "username",
                "ul_email",
                "password",
                "telephone_number",
                "user_type",
                "gender",
                "account_status"
            ]
        },
        "UpdateUser": {
            "title": "UpdateUser",
            "example": {
                "message": "User updated successfully",
                "data": {
                    "id": "57864d18-636b-48fe-8467-4652bfe1722c",
                    "schoolink_record_id": "bbkdkejdj8jdhdyeue",
                    "username": "001121",
                    "password": "5ebe2294ecd0e0f08eab7690d2a6ee69",
                    "ul_email": "johndoeul@example.com",
                    "personal_email": "johndoe@example.com",
                    "telephone_number": "0888522524",
                    "user_type": "student",
                    "gender": "Male",
                    "college": "College of Business and Public Administration (BBA/BPA)",
                    "department": "Department of Business Adm. in Accounting â€“ BBA",
                    "major": "My new major",
                    "account_status": "active",
                    "created_at": "2020-07-20T01:14:53.58Z",
                    "updated_at": "2020-07-20T01:18:39.665Z"
                }
            },
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/Data"
                }
            },
            "required": [
                "message",
                "data"
            ]
        },
        "DeleteUser": {
            "title": "DeleteUser",
            "example": {
                "message": "User deleted successfully"
            },
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            },
            "required": [
                "message"
            ]
        }
    },
    "security": [{
        "authorization": []
    }],
    "tags": [{
        "name": "Misc",
        "description": ""
    }]
}